# Generated by Django 5.2.11 on 2026-02-26 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField()),
                ('address_line1', models.CharField()),
                ('address_line2', models.CharField()),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=30)),
                ('zip', models.IntegerField(max_length=10)),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
