# Generated by Django 5.2.11 on 2026-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address_line1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address_line2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
