# Generated by Django 5.2.11 on 2026-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
