# Generated by Django 5.2.11 on 2026-02-25 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('price', models.CharField(verbose_name='Цена товара: ')),
                ('preview', models.ImageField(upload_to='shop/preview/', verbose_name='Превью')),
                ('image', models.ImageField(upload_to='shop/images/', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True)),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
