# Generated by Django 5.2.11 on 2026-02-23 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Фото')),
                ('short_description', models.CharField(max_length=50, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='instagram/photo/', verbose_name='Фото на странице')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatchOfChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('short_description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/watches/choices/', verbose_name='Выборы часов')),
            ],
            options={
                'verbose_name': 'Часы на выбор',
                'verbose_name_plural': 'Часы на выбор',
            },
        ),
    ]
